require_relative("support/fake_stdin")
require_relative("../src/command_reader")
require_relative("../src/position")
require_relative("../src/table")
require_relative("../src/robot")
require_relative("../src/toy_robot")
